version: '3.7'

services:
  postgres:
    image: 'postgres:13.7'
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    ports:
      - 54321:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
